\set ON_ERROR_STOP on

REVOKE ALL ON SCHEMA auth, chat, files FROM nchat_app;
GRANT USAGE ON SCHEMA auth, chat, files TO nchat_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA auth, chat, files TO nchat_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA auth, chat, files TO nchat_app;

ALTER DEFAULT PRIVILEGES FOR ROLE nchat_migrator IN SCHEMA auth
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nchat_app;
ALTER DEFAULT PRIVILEGES FOR ROLE nchat_migrator IN SCHEMA chat
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nchat_app;
ALTER DEFAULT PRIVILEGES FOR ROLE nchat_migrator IN SCHEMA files
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nchat_app;
ALTER DEFAULT PRIVILEGES FOR ROLE nchat_migrator IN SCHEMA auth
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO nchat_app;
ALTER DEFAULT PRIVILEGES FOR ROLE nchat_migrator IN SCHEMA chat
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO nchat_app;
ALTER DEFAULT PRIVILEGES FOR ROLE nchat_migrator IN SCHEMA files
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO nchat_app;
