port: REPLACE_ME_LIVEKIT_API_PORT
rtc:
  tcp_port: REPLACE_ME_LIVEKIT_RTC_TCP_PORT
  udp_port: REPLACE_ME_LIVEKIT_RTC_UDP_PORT
  use_external_ip: false
  node_ip: REPLACE_ME_NODE_IP
  turn_servers:
    - host: REPLACE_ME_HOST
      port: REPLACE_ME_TURN_LISTEN_PORT
      protocol: udp
      secret: REPLACE_ME
turn:
  enabled: false
logging:
  level: info
  json: true
room:
  auto_create: true
  empty_timeout: 300
  max_participants: 20
