apiVersion: v1
kind: Secret
metadata:
  name: nchat-secrets
  namespace: nchat
type: Opaque
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  VALKEY_PASSWORD: "REPLACE_ME"
  AUTH_JWT_HMAC_SECRET: "REPLACE_ME_MIN_32_BYTES"
  FILE_ENCRYPTION_KEY: "REPLACE_ME"
