listening-port=REPLACE_ME_TURN_LISTEN_PORT
min-port=REPLACE_ME_TURN_RELAY_MIN_PORT
max-port=REPLACE_ME_TURN_RELAY_MAX_PORT
realm=REPLACE_ME_HOST
use-auth-secret
REPLACE_ME_STATIC_AUTH_LINE
fingerprint
stale-nonce=600
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=198.18.0.0-198.19.255.255
denied-peer-ip=224.0.0.0-255.255.255.255
allowed-peer-ip=REPLACE_ME_NODE_IP
no-multicast-peers
no-cli
no-tls
no-dtls
log-file=stdout
pidfile=/tmp/turnserver.pid
simple-log
