apiVersion: v1
kind: Service
metadata:
  name: nchat-admin-web
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: admin-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/component: admin-web
  ports:
    - name: http
      port: 80
      targetPort: http
