- op: replace
  path: /metadata/name
  value: nchat-staging
- op: add
  path: /metadata/labels/app.kubernetes.io~1instance
  value: k3s-staging
- op: add
  path: /metadata/labels/nchat.nicrepository.io~1environment
  value: k3s-staging
- op: add
  path: /metadata/annotations
  value:
    nchat.nicrepository.io/overlay: k3s-staging
