version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - type:ci
      - technical-debt

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - type:ci
      - technical-debt

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - type:ci
      - technical-debt

  - package-ecosystem: gomod
    directory: /libs/go/platform
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - type:ci
      - technical-debt

  - package-ecosystem: gomod
    directory: /services/auth-service
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - type:ci
      - technical-debt

  - package-ecosystem: gomod
    directory: /services/chat-service
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - type:ci
      - technical-debt

  - package-ecosystem: gomod
    directory: /services/file-service
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - type:ci
      - technical-debt

  - package-ecosystem: gomod
    directory: /services/notification-service
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - type:ci
      - technical-debt

  - package-ecosystem: gomod
    directory: /services/admin-service
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - type:ci
      - technical-debt

  - package-ecosystem: gomod
    directory: /services/search-service
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - type:ci
      - technical-debt

  - package-ecosystem: gomod
    directory: /services/media-service
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - type:ci
      - technical-debt
