apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: nchat
spec:
  template:
    spec:
      containers:
        - name: media-service
          envFrom:
            - configMapRef:
                name: nchat-config
          env:
            - name: LIVEKIT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: nchat-dev-topology
                  key: LIVEKIT_API_URL
