api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":8080"
  traefik:
    address: ":8081"

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO

accessLog: {}

ping:
  entryPoint: web
