api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":8080"
  websecure:
    address: ":8443"
  dashboard:
    address: ":8081"

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO

accessLog: {}

ping:
  entryPoint: web
