apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: media
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/component: media
  ports:
    - name: http
      port: 8087
      targetPort: http
