package httpapi

const (
	RouteHealthz                  = "/healthz"
	RouteReadyz                   = "/readyz"
	RouteVersion                  = "/version"
	RouteAdminUsers               = "/admin/users"
	RouteAdminInvites             = "/admin/invites"
	RouteAuthRefresh              = "/auth/refresh"
	RouteAuthLogout               = "/auth/logout"
	RouteAuthLogin                = "/auth/login"
	RouteAuthPasswordForgot       = "/auth/password/forgot"
	RouteAuthPasswordReset        = "/auth/password/reset"
	RouteAuthInvitesAccept        = "/auth/invites/accept"
	RouteAuthMe                   = "/auth/me"
	RouteAuthMeLoginAttempts      = "/auth/me/login-attempts"
	RouteAuthMeSessions           = "/auth/me/sessions"
	RouteAuthMeSessionByID        = "/auth/me/sessions/{session_id}"
	RouteAuthMeDevices            = "/auth/me/devices"
	RouteAuthMeDeviceByID         = "/auth/me/devices/{device_id}"
	RouteAuthMeAvatar             = "/auth/me/avatar"
	RouteAuthAvatarByName         = "/auth/avatars/{name}"
	RouteAuthOIDCKeycloakLogin    = "/auth/oidc/keycloak/login"
	RouteAuthOIDCKeycloakCallback = "/auth/oidc/keycloak/callback"
	RouteAuthOIDCKeycloakExchange = "/auth/oidc/keycloak/exchange"
	RouteAdminUserStatus          = "/admin/users/{id}/status"
)
