apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: notification
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/component: notification
  ports:
    - name: http
      port: 8084
      targetPort: http
