#!/usr/bin/env bash
# Behaviour tests for the production Blue/Green operations (issue #626).
#
# These assert observable behaviour and exit codes against a fake kubectl, never
# internals: what the scripts do to the Service selectors, what they refuse, and
# — the property the review found missing — what a second run does. A rollback
# that reverses itself on retry is indistinguishable from a correct one until it
# is executed twice, so every mutation is executed twice here.
#
# No cluster, no network.
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
SCRIPTS="$ROOT_DIR/scripts/deploy/nchat-prod"
FAKE_BIN="$(mktemp -d "${TMPDIR:-/tmp}/nchat-prod-fakebin.XXXXXX")"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/nchat-prod-tests.XXXXXX")"
trap 'rm -rf "$FAKE_BIN" "$WORK"' EXIT

cp "$ROOT_DIR/scripts/ci/testdata/nchat-prod/fake-kubectl" "$FAKE_BIN/kubectl"
chmod +x "$FAKE_BIN/kubectl"
PATH="$FAKE_BIN:$PATH"
export PATH

SERVICES=(nchat-web nchat-admin-web auth-service chat-service file-service
  document-converter notification-service admin-service search-service media-service)
FAILURES=0
CASE=""
CASE_FAILURES=0

fail() { echo "  [FAIL] $CASE: $*" >&2; FAILURES=$((FAILURES + 1)); }

# Opens a case and closes the previous one. Tracking the failure count per case
# is what stops a case that already reported [FAIL] from also printing [OK].
begin() {
  CASE="$1"
  CASE_FAILURES="$FAILURES"
  # Reset the per-case release override. "RELEASE_SHA=x status=0" is a plain
  # assignment, not a command prefix, so without this a case that deliberately
  # supplies a bad SHA leaks it into every case after it. EVIDENCE is the same
  # kind of assignment and leaks the same way.
  RELEASE_SHA=""
  EVIDENCE=""
  MANIFEST_DIR=""
}

pass() {
  [[ "$FAILURES" -eq "$CASE_FAILURES" ]] || return 0
  echo "  [OK]   $CASE"
}

assert_equals() {
  local what="$1" expected="$2" actual="$3"
  [[ "$expected" == "$actual" ]] || fail "$what: expected [$expected], got [$actual]"
}

# The release every fixture slot carries unless a case changes it.
RELEASE_A=a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0
RELEASE_B=b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1

# A release is a commit AND the sealed build of it, because two builds of one
# commit do not produce the same image digests. The identities below are the
# real seals of real manifests, generated by release-manifest.sh: a fixture that
# invented a plausible-looking hash would not exercise the check that the
# promotion re-derives the identity from the manifest it is handed.
# shellcheck source=scripts/deploy/nchat-prod/release-manifest.sh
source "$SCRIPTS/release-manifest.sh"

MANIFEST_ROOT="$WORK/manifests"

# A sealed manifest for one commit. `salt` stands in for what a rebuild changes:
# same commit, same image inventory, different bytes and so different digests.
make_release_manifest() {
  local name="$1" source_sha="$2" salt="${3-}" image
  local digests="$MANIFEST_ROOT/digests.$name" out="$MANIFEST_ROOT/$name"
  rm -rf "$digests" "$out"
  mkdir -p "$digests"
  for image in "${NCHAT_DEV_IMAGES[@]}"; do
    printf 'sha256:%s' "$(printf '%s%s' "$image" "$salt" | sha256sum | cut -d' ' -f1)" \
      >"$digests/digest-$image.txt"
  done
  NCHAT_RELEASE_SOURCE_SHA="$source_sha" NCHAT_RELEASE_RUN_ID=1234 \
    bash "$SCRIPTS/release-manifest.sh" "$digests" "$out" >/dev/null
  printf '%s' "$out"
}

release_id_of() { cut -d ' ' -f1 <"$1/release-manifest.sha256"; }

# A manifest edited and sealed again, so `sha256sum -c` passes and only the
# release contract itself can refuse it. Without re-sealing, every such case
# would be caught by the seal and the contract would never be exercised.
reseal_manifest() {
  local name="$1" edit="$2"
  local out="$MANIFEST_ROOT/resealed.$name"
  rm -rf "$out"; cp -a "$MANIFEST_A" "$out"
  jq "$edit" "$MANIFEST_A/release-manifest.json" >"$out/release-manifest.json"
  (cd "$out" && sha256sum release-manifest.json >release-manifest.sha256)
  printf '%s' "$out"
}

MANIFEST_A="$(make_release_manifest a "$RELEASE_A")"
MANIFEST_B="$(make_release_manifest b "$RELEASE_B")"
# Same commit as B, rebuilt. This is the release the source SHA cannot tell
# apart from B, and the one the identity exists to catch.
MANIFEST_B_REBUILT="$(make_release_manifest b-rebuilt "$RELEASE_B" rebuilt)"
# Same commit as A, rebuilt: the pair that proves the images and the identity
# travel together, since only the digests distinguish them.
MANIFEST_A_REBUILT="$(make_release_manifest a-rebuilt "$RELEASE_A" rebuilt)"
RELEASE_ID_A="$(release_id_of "$MANIFEST_A")"
RELEASE_ID_B="$(release_id_of "$MANIFEST_B")"
RELEASE_ID_B_REBUILT="$(release_id_of "$MANIFEST_B_REBUILT")"
RELEASE_ID_A_REBUILT="$(release_id_of "$MANIFEST_A_REBUILT")"

# The digest a manifest seals for one image, and the digests a rendered manifest
# actually pins. Comparing these is what proves the images and the identity came
# from the same release rather than merely being present together.
manifest_digest() {
  jq -r --arg image "$2" '.images[$image]' "$1/release-manifest.json"
}

applied_image_digest() {
  local state="$1" manifest="$2" image="$3"
  awk -v needle="/nchat/$image@" '$1 == "image:" && index($2, needle) { print $2 }' \
    "$state/applied/$manifest" 2>/dev/null | sed 's/.*@//' | sort -u
}

# What a workload's Ready pods report, and what the smoke evidence names.
identity() { printf '%s:%s' "$1" "$2"; }
evidence() { printf '%s:%s:%s' "$1" "$2" "$3"; }
# The Secrets bootstrap requires before it will touch the namespace.
REQUIRED_SECRETS=(nchat-secrets nchat-postgres-runtime nchat-postgres-migrator
  nchat-file-encryption ghcr-pull)
# Services the shared stateful layer must already publish.
REQUIRED_STATEFUL=(postgres valkey seaweedfs-filer)

# The replica count each workload really runs in production.
#
# auth-service is one, not two: its avatar volume is ReadWriteOnce and a single
# replica owns writes. The fixture says two everywhere only if nobody checks the
# manifests, and a fake that disagrees with production tests the wrong system.
replicas_for() {
  [[ "$1" == "auth-service" ]] && printf '1' || printf '2'
}

# Builds a cluster: every Service on $1, every Deployment of the slots in $2 Ready.
new_state() {
  local active="$1" ready_slots="$2" state slot service secret count
  state="$WORK/state.$RANDOM"
  mkdir -p "$state/services" "$state/ready" "$state/sha" "$state/image" "$state/secrets"
  printf 'nchat-prod-deployer' >"$state/context"
  printf 'nchat-prod' >"$state/namespace"
  : >"$state/patch-log"
  for secret in "${REQUIRED_SECRETS[@]}"; do
    : >"$state/secrets/$secret"
  done
  # A cluster with room to spare: the deploy cases are about migrations and
  # rollouts, so capacity must not be what decides them. The preflight itself
  # has its own fixtures in test_prod_capacity_preflight.sh.
  mkdir -p "$state/quota"
  printf '16' >"$state/quota/hard-cpu"; printf '1' >"$state/quota/used-cpu"
  printf '32Gi' >"$state/quota/hard-memory"; printf '2Gi' >"$state/quota/used-memory"
  printf '80' >"$state/quota/hard-pods"; printf '10' >"$state/quota/used-pods"
  printf '500Gi' >"$state/quota/hard-storage"; printf '10Gi' >"$state/quota/used-storage"
  printf '32 128Gi 500Gi 220\n' >"$state/node-allocatable"
  printf 'Running|node-a|500m 2Gi 1Gi\n' >"$state/cluster-pods"
  printf 'Running|node-a\n' >"$state/cluster-pod-slots"
  mkdir -p "$state/jobs"
  printf 'nchat-migrations-%s\n' "${RELEASE_A:0:12}" >"$state/pending-job-name"
  for service in "${REQUIRED_STATEFUL[@]}"; do
    printf 'shared' >"$state/services/$service"
  done
  for service in "${SERVICES[@]}"; do
    [[ "$active" == "none" ]] || printf '%s' "$active" >"$state/services/$service"
  done
  for slot in $ready_slots; do
    for service in "${SERVICES[@]}"; do
      count="$(replicas_for "$service")"
      set_rollout "$state" "$service-$slot" 1 1 "$count" "$count" "$count" "$count" 0
      set_release "$state" "$service" "$slot" "$RELEASE_A"
      printf 'ghcr.io/nicrepository/nchat/%s@sha256:%064d' "$service" 1 >"$state/image/$service-$slot"
    done
  done
  printf '%s' "$state"
}

# The component label a Deployment selects on, mirroring the real manifests.
component_for() {
  case "$1" in
    nchat-web) printf 'web' ;;
    nchat-admin-web) printf 'admin-web' ;;
    auth-service) printf 'auth' ;;
    chat-service) printf 'chat' ;;
    file-service) printf 'file' ;;
    document-converter) printf 'document-converter' ;;
    notification-service) printf 'notification' ;;
    admin-service) printf 'admin' ;;
    search-service) printf 'search' ;;
    media-service) printf 'media' ;;
  esac
}

# generation observedGeneration replicas updated ready available unavailable
set_rollout() {
  local state="$1" deployment="$2"
  shift 2
  printf '%s %s %s %s %s %s %s\n' "$@" >"$state/ready/$deployment"
}

# Sets both the release the Deployment declares and the one its Ready pods run.
# A third argument makes them differ, which is what a stuck rollout looks like.
set_release() {
  local state="$1" service="$2" slot="$3" desired="$4" observed="${5:-$4}" component
  component="$(component_for "$service")"
  mkdir -p "$state/observed" "$state/component"
  printf '%s' "$desired" >"$state/sha/$service-$slot"
  printf '%s' "$component" >"$state/component/$service-$slot"
  # The pods report the whole identity, commit and sealed build together, which
  # is what the promotion compares against the manifest it is handed.
  printf '%s\n' "$(identity "$observed" "$(default_release_id "$observed")")" \
    >"$state/observed/$component-$slot"
}

# Moves one workload of a slot onto a different release, the shape a deploy that
# failed part-way leaves behind.
# `release_id` defaults to the sealed manifest of that commit, so a case that
# only cares about the SHA keeps reading the way it did. A case testing the
# identity names one explicitly -- including the empty string, which is what a
# workload deployed before the annotation existed reports.
set_workload_release() {
  local state="$1" deployment="$2" release="$3" release_id="${4-}" service slot component
  slot="${deployment##*-}"
  service="${deployment%-"$slot"}"
  component="$(component_for "$service")"
  [[ "$#" -ge 4 ]] || release_id="$(default_release_id "$release")"
  printf '%s' "$release" >"$state/sha/$deployment"
  printf '%s\n' "$(identity "$release" "$release_id")" >"$state/observed/$component-$slot"
}

default_release_id() {
  case "$1" in
    "$RELEASE_A") printf '%s' "$RELEASE_ID_A" ;;
    "$RELEASE_B") printf '%s' "$RELEASE_ID_B" ;;
    *) printf '%s' "$(printf '%s' "$1" | sha256sum | cut -d' ' -f1)" ;;
  esac
}

slot_of() { cat "$1/services/$2" 2>/dev/null || printf 'unset'; }

# Asserts every Service selects $2.
assert_all_on() {
  local state="$1" expected="$2" service actual
  for service in "${SERVICES[@]}"; do
    actual="$(slot_of "$state" "$service")"
    [[ "$actual" == "$expected" ]] || { fail "service/$service is '$actual', expected '$expected'"; return; }
  done
}

run() {
  local state="$1"; shift
  FAKE_STATE_DIR="$state" NCHAT_PROD_ASSUME_YES=1 NCHAT_PROD_SMOKE_CONFIRMED="${SMOKE:-}" \
    NCHAT_PROD_RELEASE_MANIFEST_DIR="${MANIFEST_DIR:-$MANIFEST_A}" \
    "$@" >"$WORK/out.txt" 2>"$WORK/err.txt"
}

expect_exit() {
  local expected="$1" actual="$2"
  [[ "$actual" == "$expected" ]] || fail "exit $actual, expected $expected: $(tail -2 "$WORK/err.txt")"
}

echo "=== production blue/green script behaviour ==="
echo
echo "--- status ---"

begin "status reports blue active"
state="$(new_state blue "blue green")"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 0 "$status"
grep -q "ACTIVE   : blue" "$WORK/out.txt" || fail "did not report blue as active"
pass

begin "status reports green active"
state="$(new_state green "blue green")"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 0 "$status"
grep -q "ACTIVE   : green" "$WORK/out.txt" || fail "did not report green as active"
pass

begin "status detects a mixed state and exits non-zero"
state="$(new_state blue "blue green")"
printf 'green' >"$state/services/chat-service"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
grep -q "MIXED STATE" "$WORK/err.txt" || fail "did not name the mixed state"
pass

begin "status reports a slot whose workloads carry different releases"
state="$(new_state blue "blue green")"
# A genuinely half-applied slot: one workload's Ready pods are on another
# release. Writing only the Deployment's annotation would express a stale
# rollout instead, which is the separate case covered below.
set_workload_release "$state" file-service-blue "$RELEASE_B"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
grep -q "release   MIXED" "$WORK/out.txt" || fail "hid a half-applied release behind one service"
grep -q "file-service" "$WORK/out.txt" || fail "did not name the diverging workload"
pass

begin "status reports a missing Service without abandoning the rest of the map"
state="$(new_state blue "blue green")"
rm -f "$state/services/file-service"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
grep -q "file-service *-> MISSING" "$WORK/out.txt" || fail "did not report the Service as MISSING"
grep -q "chat-service *-> blue" "$WORK/out.txt" || fail "stopped before reporting the other Services"
grep -q "media-service *-> blue" "$WORK/out.txt" || fail "did not reach the end of the Service list"
grep -q "MISSING" "$WORK/out.txt" && ! grep -q "file-service *-> mixed" "$WORK/out.txt" ||
  fail "collapsed MISSING into mixed"
pass

begin "status reports a Service whose selector was never patched"
state="$(new_state blue "blue green")"
: >"$state/services/search-service"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
grep -q "search-service *-> UNSET" "$WORK/out.txt" || fail "did not distinguish an absent selector"
pass

begin "status exits non-zero when the candidate carries a mixed release"
state="$(new_state blue "blue green")"
set_workload_release "$state" chat-service-green "$RELEASE_B"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
grep -q "state     INVALID" "$WORK/out.txt" || fail "did not mark the candidate invalid"
grep -q "chat-service" "$WORK/out.txt" || fail "did not name the diverging workload"
grep -q "ACTIVE   : blue" "$WORK/out.txt" || fail "did not print the full picture first"
pass

begin "status reports an undeployed candidate as such, not as an error"
state="$(new_state blue "blue")"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 0 "$status"
grep -q "state     NOT DEPLOYED" "$WORK/out.txt" || fail "did not distinguish an undeployed slot"
pass

begin "status fails on an unexpected kube context"
state="$(new_state blue "blue green")"
printf 'some-other-cluster' >"$state/context"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
grep -q "expected 'nchat-prod-deployer'" "$WORK/err.txt" || fail "did not refuse the context"
pass

begin "status fails when the namespace is absent"
state="$(new_state blue "blue green")"
printf 'nchat-dev' >"$state/namespace"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
pass

echo
echo "--- rollout observation ---"

# Readiness used to be readyReplicas == spec.replicas, which the pods of the
# release being REPLACED satisfy. Every case below keeps that comparison true
# and must still be refused.
begin "a fully rolled out workload is ready"
state="$(new_state blue "blue green")"
set_rollout "$state" chat-service-green 2 2 2 2 2 2 0
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 0 "$status"
pass

begin "a generation the controller has not observed is not ready"
state="$(new_state blue "blue green")"
set_rollout "$state" chat-service-green 4 3 2 2 2 2 0
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
grep -q "ROLLING OUT" "$WORK/out.txt" || fail "a stale observedGeneration was reported as settled"
pass

begin "old pods still Ready do not make a stuck rollout ready"
state="$(new_state blue "blue green")"
# Green declares B; its new pods never scheduled, so the two Ready pods are the
# A pods it is replacing.
set_rollout "$state" chat-service-green 2 2 2 0 2 2 0
set_release "$state" chat-service green "$RELEASE_B" "$RELEASE_A"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
grep -q "ROLLING OUT" "$WORK/out.txt" || fail "reported a stuck rollout as a finished release"
grep -q "observed=$RELEASE_A" "$WORK/out.txt" || fail "did not report the release actually running"
pass

begin "a partial rollout is not ready"
state="$(new_state blue "blue green")"
set_rollout "$state" chat-service-green 2 2 2 1 2 2 0
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
pass

begin "updated but not available is not ready"
state="$(new_state blue "blue green")"
set_rollout "$state" chat-service-green 2 2 2 2 2 1 0
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
pass

begin "any unavailable replica means not ready"
state="$(new_state blue "blue green")"
set_rollout "$state" chat-service-green 2 2 2 2 2 2 1
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
pass

begin "a stuck rollout produces no smoke evidence"
state="$(new_state blue "blue green")"
set_rollout "$state" chat-service-green 2 2 2 0 2 2 0
set_release "$state" chat-service green "$RELEASE_B" "$RELEASE_A"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target green || status=$?
expect_exit 1 "$status"
grep -q "has not finished rolling out" "$WORK/err.txt" || fail "smoked a slot that never rolled out"
grep -q "NCHAT_PROD_SMOKE_CONFIRMED=green:$RELEASE_B" "$WORK/out.txt" &&
  fail "emitted evidence for a release that is not running"
pass

begin "a stuck rollout cannot be promoted even with evidence in hand"
state="$(new_state blue "blue green")"
set_rollout "$state" chat-service-green 2 2 2 0 2 2 0
set_release "$state" chat-service green "$RELEASE_B" "$RELEASE_A"
SMOKE="$(evidence green "$RELEASE_B" "$RELEASE_ID_B")" MANIFEST_DIR="$MANIFEST_B" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
[[ ! -s "$state/patch-log" ]] || fail "promoted a slot whose Ready pods are the previous release"
pass

echo
echo "--- cutover ---"

begin "cutover blue -> green converges every service"
state="$(new_state blue "blue green")"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 0 "$status"
assert_all_on "$state" green
pass

begin "cutover green -> blue converges every service"
state="$(new_state green "blue green")"
SMOKE="$(evidence blue "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target blue || status=$?
expect_exit 0 "$status"
assert_all_on "$state" blue
pass

begin "repeating a cutover is a no-op, not a reversal"
state="$(new_state blue "blue green")"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" run "$state" "$SCRIPTS/cutover.sh" --target green || fail "first cutover failed"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 0 "$status"
assert_all_on "$state" green
grep -q "nothing to move" "$WORK/out.txt" || fail "did not report a no-op"
pass

begin "cutover converges a mixed state onto the named target"
state="$(new_state blue "blue green")"
printf 'green' >"$state/services/chat-service"
printf 'green' >"$state/services/file-service"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 0 "$status"
assert_all_on "$state" green
pass

begin "cutover to a mixed state's other side also converges"
state="$(new_state green "blue green")"
printf 'blue' >"$state/services/chat-service"
SMOKE="$(evidence blue "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target blue || status=$?
expect_exit 0 "$status"
assert_all_on "$state" blue
pass

begin "cutover refuses an unhealthy target before touching anything"
state="$(new_state blue "blue")"
printf '2 0\n' >"$state/ready/chat-service-green"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
[[ ! -s "$state/patch-log" ]] || fail "patched a service despite an unhealthy target"
pass

begin "cutover refuses an invalid target before any mutation"
state="$(new_state blue "blue green")"
SMOKE=purple status=0; run "$state" "$SCRIPTS/cutover.sh" --target purple || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
grep -q "target slot is required" "$WORK/err.txt" || fail "did not reject the target"
pass

begin "cutover with no target at all is refused"
state="$(new_state blue "blue green")"
status=0; run "$state" "$SCRIPTS/cutover.sh" || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
pass

begin "cutover without recorded smoke evidence is blocked"
state="$(new_state blue "blue green")"
SMOKE="" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
grep -q "authenticated release smoke" "$WORK/err.txt" || fail "did not require the manual smoke"
pass

begin "a patch failure part-way leaves a mixed state the operator can see"
state="$(new_state blue "blue green")"
printf 'file-service\n' >"$state/patch-fails"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
grep -q "mixed state" "$WORK/err.txt" || fail "did not report the partial failure"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
grep -q "MIXED STATE" "$WORK/err.txt" || fail "status hid the partial cutover"
pass

begin "re-running after a partial failure converges to the same target"
rm -f "$state/patch-fails"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 0 "$status"
assert_all_on "$state" green
pass

begin "cutover is blocked when the candidate carries more than one release"
state="$(new_state blue "blue green")"
set_workload_release "$state" chat-service-green "$RELEASE_B"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
[[ ! -s "$state/patch-log" ]] || fail "promoted a slot carrying two releases"
grep -q "does not carry one release" "$WORK/err.txt" || fail "did not name the inconsistency"
pass

begin "cutover is blocked when the candidate changed after the smoke"
state="$(new_state blue "blue green")"
for svc in "${SERVICES[@]}"; do set_workload_release "$state" "$svc-green" "$RELEASE_B"; done
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_B" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
grep -q "does not match" "$WORK/err.txt" || fail "accepted evidence for a superseded release"
pass

# The case a source SHA cannot see.
#
# Between the smoke and the approval the candidate is rebuilt from the very same
# commit. buildx stamps provenance and an SBOM into every layer set, so the
# image digests differ and the slot is now running bytes nobody validated -- yet
# every SHA in sight still reads $RELEASE_B. What separates them is the sealed
# manifest: a different build seals a different manifest, and the promotion
# re-derives that identity instead of trusting what it was handed.
begin "cutover is blocked when the candidate was rebuilt from the same commit"
state="$(new_state blue "blue green")"
for svc in "${SERVICES[@]}"; do
  set_workload_release "$state" "$svc-green" "$RELEASE_B" "$RELEASE_ID_B_REBUILT"
done
SMOKE="$(evidence green "$RELEASE_B" "$RELEASE_ID_B")" MANIFEST_DIR="$MANIFEST_B" status=0
run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
[[ ! -s "$state/patch-log" ]] || fail "promoted a rebuild of the smoked commit"
grep -q "$RELEASE_ID_B_REBUILT" "$WORK/err.txt" || fail "did not name the release actually on the slot"
pass

# A half-formed identity is not a release. Reporting it as one would let a
# "wrong release" message stand in for "these pods say nothing", which are
# different faults with different fixes, so the state is refused as such.
begin "cutover is blocked when the workloads carry no release identity"
state="$(new_state blue "blue green")"
for svc in "${SERVICES[@]}"; do set_workload_release "$state" "$svc-green" "$RELEASE_B" ""; done
SMOKE="$(evidence green "$RELEASE_B" "$RELEASE_ID_B")" MANIFEST_DIR="$MANIFEST_B" status=0
run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
grep -q "does not carry one release" "$WORK/err.txt" ||
  fail "a workload with no release identity was reported as carrying a release"
pass

begin "cutover is blocked when the workloads disagree about the release identity"
state="$(new_state blue "blue green")"
for svc in "${SERVICES[@]}"; do set_workload_release "$state" "$svc-green" "$RELEASE_B" "$RELEASE_ID_B"; done
set_workload_release "$state" "media-service-green" "$RELEASE_B" "$RELEASE_ID_B_REBUILT"
SMOKE="$(evidence green "$RELEASE_B" "$RELEASE_ID_B")" MANIFEST_DIR="$MANIFEST_B" status=0
run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
pass

# The identity is only worth anything if it is re-derived rather than accepted,
# so the promotion refuses to run at all without the manifest to derive it from.
begin "cutover is blocked when no sealed manifest is supplied"
state="$(new_state blue "blue green")"
for svc in "${SERVICES[@]}"; do set_workload_release "$state" "$svc-green" "$RELEASE_B"; done
SMOKE="$(evidence green "$RELEASE_B" "$RELEASE_ID_B")" MANIFEST_DIR="$WORK/no-such-manifest" status=0
run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
pass

# A manifest edited after it was sealed identifies nothing, so it cannot be used
# to authorise a promotion however well its contents read.
begin "cutover is blocked when the supplied manifest is not sealed"
state="$(new_state blue "blue green")"
tampered="$WORK/tampered-manifest"
rm -rf "$tampered"; cp -a "$MANIFEST_B" "$tampered"
printf 'tampered' >>"$tampered/release-manifest.json"
for svc in "${SERVICES[@]}"; do set_workload_release "$state" "$svc-green" "$RELEASE_B"; done
SMOKE="$(evidence green "$RELEASE_B" "$RELEASE_ID_B")" MANIFEST_DIR="$tampered" status=0
run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
pass

begin "smoke evidence naming the slot and commit but not the build is not accepted"
state="$(new_state blue "blue green")"
for svc in "${SERVICES[@]}"; do set_workload_release "$state" "$svc-green" "$RELEASE_B"; done
SMOKE="green:$RELEASE_B" MANIFEST_DIR="$MANIFEST_B" status=0
run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
pass

begin "cutover proceeds when the smoke evidence matches the current release"
state="$(new_state blue "blue green")"
for svc in "${SERVICES[@]}"; do set_workload_release "$state" "$svc-green" "$RELEASE_B"; done
SMOKE="$(evidence green "$RELEASE_B" "$RELEASE_ID_B")" MANIFEST_DIR="$MANIFEST_B" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 0 "$status"
assert_all_on "$state" green
pass

begin "smoke evidence naming only the slot is not accepted"
state="$(new_state blue "blue green")"
SMOKE=green status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
pass

begin "cutover is blocked when the candidate is not deployed at all"
state="$(new_state blue "blue")"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
assert_all_on "$state" blue
pass

echo
echo "--- rollback ---"

begin "rollback green -> blue converges every service"
state="$(new_state green "blue green")"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "5xx after cutover" || status=$?
expect_exit 0 "$status"
assert_all_on "$state" blue
pass

begin "repeating a rollback does not send production back to the bad release"
state="$(new_state green "blue green")"
run "$state" "$SCRIPTS/rollback.sh" --target blue "5xx after cutover" || fail "first rollback failed"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "5xx after cutover" || status=$?
expect_exit 0 "$status"
assert_all_on "$state" blue
grep -q "nothing to move" "$WORK/out.txt" || fail "did not report a no-op on retry"
pass

begin "rollback blue -> green is possible when explicitly asked for"
state="$(new_state blue "blue green")"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target green "blue baseline is faulty" || status=$?
expect_exit 0 "$status"
assert_all_on "$state" green
pass

begin "rollback requires a reason"
state="$(new_state green "blue green")"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue || status=$?
expect_exit 1 "$status"
assert_all_on "$state" green
pass

begin "rollback refuses an unhealthy target rather than choosing another slot"
state="$(new_state green "green")"
printf '2 0\n' >"$state/ready/auth-service-blue"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "incident" || status=$?
expect_exit 1 "$status"
assert_all_on "$state" green
[[ ! -s "$state/patch-log" ]] || fail "moved traffic onto a slot that cannot serve it"
pass

begin "rollback converges a mixed state onto the named target"
state="$(new_state green "blue green")"
printf 'blue' >"$state/services/chat-service"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "mixed after failed cutover" || status=$?
expect_exit 0 "$status"
assert_all_on "$state" blue
pass

begin "a rollback that fails part-way reports it and can be re-run"
state="$(new_state green "blue green")"
printf 'search-service\n' >"$state/patch-fails"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "incident" || status=$?
expect_exit 1 "$status"
rm -f "$state/patch-fails"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "incident" || status=$?
expect_exit 0 "$status"
assert_all_on "$state" blue
pass

begin "rollback is blocked when the target is Ready but carries a mixed release"
state="$(new_state green "blue green")"
set_workload_release "$state" chat-service-blue "$RELEASE_B"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "incident" || status=$?
expect_exit 1 "$status"
assert_all_on "$state" green
[[ ! -s "$state/patch-log" ]] || fail "moved traffic onto a slot carrying two releases"
grep -q "does not carry one release" "$WORK/err.txt" || fail "did not name the inconsistency"
pass

begin "rollback to an already-active slot with a mixed release is a failure, not a no-op"
state="$(new_state blue "blue green")"
set_workload_release "$state" file-service-blue "$RELEASE_B"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "incident" || status=$?
expect_exit 1 "$status"
grep -q "does not carry one release" "$WORK/err.txt" || fail "reported a mixed active slot as success"
grep -q "No change made" "$WORK/out.txt" && fail "claimed a clean no-op over a mixed release"
pass

begin "rollback to an already-active consistent slot is a validated no-op"
state="$(new_state blue "blue green")"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "checking" || status=$?
expect_exit 0 "$status"
grep -q "carrying release $RELEASE_A" "$WORK/out.txt" || fail "did not report the validated release"
[[ ! -s "$state/patch-log" ]] || fail "patched a Service during a no-op"
pass

begin "rollback is blocked when the target is not deployed at all"
state="$(new_state green "green")"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "incident" || status=$?
expect_exit 1 "$status"
assert_all_on "$state" green
pass

begin "rollback converges mixed Services onto a consistent target"
# Mixed Services is a different fault from a mixed release inside one slot, and
# only the first is something rollback should fix.
state="$(new_state green "blue green")"
printf 'blue' >"$state/services/chat-service"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "converge after failed cutover" || status=$?
expect_exit 0 "$status"
assert_all_on "$state" blue
pass

begin "rollback fails when the target release breaks during convergence"
state="$(new_state green "blue green")"
printf 'search-service' >"$state/patch-fails"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "incident" || status=$?
expect_exit 1 "$status"
# The partial patch is visible, and re-running must still be possible.
rm -f "$state/patch-fails"
set_workload_release "$state" media-service-blue "$RELEASE_B"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "incident" || status=$?
expect_exit 1 "$status"
grep -q "does not carry one release" "$WORK/err.txt" || fail "resumed onto an inconsistent slot"
pass

echo
echo "--- drain-old ---"

begin "drain-old refuses to scale down the slot serving traffic"
state="$(new_state blue "blue green")"
status=0; run "$state" "$SCRIPTS/drain-old.sh" --target blue || status=$?
expect_exit 1 "$status"
[[ ! -f "$state/scale-log" ]] || fail "scaled down the active slot"
pass

begin "drain-old scales the retired slot to zero"
state="$(new_state blue "blue green")"
status=0; run "$state" "$SCRIPTS/drain-old.sh" --target green || status=$?
expect_exit 0 "$status"
[[ "$(wc -l <"$state/scale-log")" -eq "${#SERVICES[@]}" ]] || fail "did not scale every workload"
pass

echo
echo "--- smoke ---"

begin "smoke never reports a bare pass and blocks cutover"
state="$(new_state blue "blue green")"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target green || status=$?
expect_exit 0 "$status"
grep -q "Automated smoke            : PASS" "$WORK/out.txt" || fail "no automated verdict"
grep -q "NOT CONFIRMED BY THIS COMMAND" "$WORK/out.txt" || fail "did not flag the manual smoke"
grep -q "Cutover eligibility        : BLOCKED" "$WORK/out.txt" || fail "did not block cutover"
grep -qx "smoke passed" "$WORK/out.txt" && fail "claimed an unqualified pass"
pass

begin "smoke fails when the candidate carries more than one release"
state="$(new_state blue "blue green")"
set_workload_release "$state" file-service-green "$RELEASE_B"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target green || status=$?
expect_exit 1 "$status"
grep -q "more than one release" "$WORK/err.txt" || fail "smoked an incoherent candidate"
grep -q "Release validated          : NONE" "$WORK/out.txt" || fail "claimed to have validated a release"
pass

begin "smoke prints evidence bound to the slot and the release"
state="$(new_state blue "blue green")"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target green || status=$?
expect_exit 0 "$status"
grep -q "NCHAT_PROD_SMOKE_CONFIRMED=green:$RELEASE_A" "$WORK/out.txt" ||
  fail "evidence is not bound to the release"
pass

begin "smoke refuses a slot that is already serving production traffic"
state="$(new_state blue "blue green")"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target blue || status=$?
expect_exit 1 "$status"
grep -q "already selected by" "$WORK/err.txt" || fail "did not detect the lack of isolation"
pass

echo
echo "--- bootstrap ---"

# Bootstrap and deploy render real Kustomize overlays and rewrite images from
# digest artefacts, so the cases below supply both. RELEASE_SHA has to look like
# a commit, because validating it is one of the gates under test.
ARTIFACTS="$WORK/artifacts"
mkdir -p "$ARTIFACTS"
for image in web admin-web auth-service chat-service file-service \
  document-converter notification-service admin-service search-service media-service migrations; do
  printf 'sha256:%064d' 1 >"$ARTIFACTS/digest-$image.txt"
done
# The deploy stamps the release identity on every workload it renders, so the
# artefacts have to carry one -- release-digests.sh writes it beside the digests
# from the manifest seal, and a deploy without it is refused.
printf '%s' "$RELEASE_ID_A" >"$ARTIFACTS/release-id.txt"
TOPOLOGY="$WORK/topology.env"
cat >"$TOPOLOGY" <<TOPO
NCHAT_PROD_HOST=nchat.example.com
NCHAT_PROD_PUBLIC_URL=https://nchat.example.com
NCHAT_PROD_PREVIEW_ALLOW_CIDR=198.51.100.0/24
NCHAT_PROD_LIVEKIT_URL=wss://livekit.example.com
NCHAT_PROD_LIVEKIT_CONNECT_SRC=wss://livekit.example.com https://livekit.example.com
TOPO

release_run() {
  local state="$1"; shift
  FAKE_STATE_DIR="$state" NCHAT_PROD_ASSUME_YES=1 \
    NCHAT_PROD_CANDIDATE_SLOT="${CANDIDATE_SLOT:-}" \
    NCHAT_PROD_RELEASE_SHA="${RELEASE_SHA:-$RELEASE_A}" \
    NCHAT_PROD_CAPACITY_EVIDENCE_DIR="${EVIDENCE:-}" \
    NCHAT_PROD_RELEASE_MANIFEST_DIR="${MANIFEST_DIR:-$MANIFEST_A}" \
    NCHAT_PROD_TOPOLOGY_FILE="$TOPOLOGY" ARTIFACTS_DIR="$ARTIFACTS" \
    "$@" >"$WORK/out.txt" 2>"$WORK/err.txt"
}

# The release annotation a rendered manifest actually carries, deduplicated
# across its workloads. Read from what was applied rather than from the fixture,
# which is the whole point: the fixture's own identity would answer for a deploy
# that never wrote one.
#
# An empty result therefore means the annotation is absent, and a result with
# two lines means the workloads disagree -- both are failures at the call site.
applied_annotation() {
  local state="$1" manifest="$2" annotation="$3"
  awk -v key="$annotation:" '$1 == key { print $2 }' \
    "$state/applied/$manifest" 2>/dev/null | sort -u
}

# Kustomize is required, never skipped.
#
# These cases exercise bootstrap and deploy — the two flows that render and apply
# production — so skipping them when the binary is missing produced a green CI
# that had tested none of it. The repository already pins and checksum-verifies
# a Kustomize; that is what gets used, exactly as scripts/security/trivy-config.sh
# does. Only a genuine failure to obtain it stops the suite, and then it stops
# rather than passing.
require_kustomize() {
  local directory
  command -v kustomize >/dev/null 2>&1 && return 0
  echo "  kustomize not on PATH; installing the pinned, checksum-verified build"
  directory="$("$ROOT_DIR/scripts/deploy/nchat-dev/install-kustomize.sh")" || return 1
  PATH="$directory:$PATH"
  export PATH
  command -v kustomize >/dev/null 2>&1
}

if ! require_kustomize; then
  echo "Kustomize is required for production Blue/Green operational tests." >&2
  echo "Install it, or make scripts/deploy/nchat-dev/install-kustomize.sh usable here." >&2
  exit 1
fi

begin "bootstrap refuses to start when the migrator Secret is absent"
state="$(new_state none "")"
rm -f "$state/secrets/nchat-postgres-migrator"
status=0; release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 1 "$status"
grep -q "missing Secret: nchat-postgres-migrator" "$WORK/err.txt" ||
  fail "did not name the missing Secret"
[[ ! -f "$state/apply-log" ]] || fail "applied resources despite a missing prerequisite"
[[ ! -f "$state/wait-log" ]] || fail "started the migration despite a missing prerequisite"
pass

begin "bootstrap refuses to start when the stateful layer is absent"
state="$(new_state none "")"
rm -f "$state/services/postgres"
status=0; release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 1 "$status"
grep -q "missing Service: postgres" "$WORK/err.txt" || fail "did not name the missing Service"
[[ ! -f "$state/apply-log" ]] || fail "applied resources despite a missing prerequisite"
pass

begin "bootstrap refuses a release that is not a commit SHA"
state="$(new_state none "")"
RELEASE_SHA=not-a-sha status=0; release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 1 "$status"
[[ ! -f "$state/apply-log" ]] || fail "applied resources for an unidentified release"
pass

begin "bootstrap stops when the migration Job fails and never establishes Blue"
state="$(new_state none "blue")"
printf '1' >"$state/migration-fails"
status=0; release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 1 "$status"
grep -qE "migration .* did not complete" "$WORK/err.txt" || fail "did not report the migration failure"
[[ ! -f "$state/rollout-log" ]] || fail "rolled out Blue after a failed migration"
pass

# Capacity is checked before the migration runs and before any workload exists:
# discovering that Blue does not fit *after* the schema has moved leaves a
# half-established production to unpick by hand.
begin "bootstrap aborts before migrations when the cluster cannot hold Blue"
state="$(new_state blue "blue")"
printf '1' >"$state/quota/hard-cpu"
printf '900m' >"$state/quota/used-cpu"
status=0; release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 1 "$status"
grep -qE "cannot hold slot .* at production capacity" "$WORK/err.txt" || fail "did not report the shortfall"
[[ ! -f "$state/wait-log" ]] || fail "ran the migration despite insufficient capacity"
[[ ! -f "$state/rollout-log" ]] || fail "deployed Blue despite insufficient capacity"
grep -q "baseline.yaml" "$state/apply-log" 2>/dev/null && fail "applied the Blue workloads anyway"
pass

begin "bootstrap aborts before migrations when capacity cannot be determined"
state="$(new_state blue "blue")"
rm -rf "$state/quota" "$state/node-allocatable" "$state/cluster-pods" "$state/cluster-pod-slots"
status=0; release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 1 "$status"
grep -q "inconclusive" "$WORK/err.txt" || fail "did not report the preflight as inconclusive"
[[ ! -f "$state/wait-log" ]] || fail "ran the migration on an unverified capacity picture"
[[ ! -f "$state/rollout-log" ]] || fail "deployed Blue on an unverified capacity picture"
pass

begin "bootstrap establishes Blue and leaves it selected"
state="$(new_state blue "blue")"
status=0; release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 0 "$status"
[[ -f "$state/wait-log" ]] || fail "never ran the migration Job"
[[ "$(wc -l <"$state/rollout-log")" -eq "${#SERVICES[@]}" ]] || fail "did not wait for every workload"
grep -q "Users must NOT be given the address yet" "$WORK/out.txt" ||
  fail "did not withhold availability until the smoke"
pass

# What the baseline is stamped with, read out of the manifest bootstrap applied.
#
# The fixture pre-populates the slot's observed identity so that `rollout status`
# has something to report, and that fixture would answer for a bootstrap which
# wrote no identity at all -- which is exactly how a baseline carrying only a
# commit went unnoticed. So these cases ignore the fixture and assert on the
# rendered baseline: the annotations below exist because bootstrap put them
# there, and the release id is compared against the manifest it was derived from.
begin "bootstrap stamps the baseline with the commit and the sealed release"
state="$(new_state blue "blue")"
status=0; release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 0 "$status"
[[ -f "$state/applied/baseline.yaml" ]] || fail "no baseline manifest was applied"
assert_equals "the baseline carries the requested commit" "$RELEASE_A" \
  "$(applied_annotation "$state" baseline.yaml nchat.io/release-sha)"
assert_equals "the baseline carries the sealed manifest's release id" "$RELEASE_ID_A" \
  "$(applied_annotation "$state" baseline.yaml nchat.io/release-id)"
pass

# An identity is only an identity if it describes the images that are running.
# The fixture deliberately leaves an unrelated set of digest artefacts lying
# around in ARTIFACTS; if bootstrap could still read them, the baseline would be
# annotated as release A while running something else entirely -- and no later
# gate compares the annotation to the images again, so nothing would notice.
begin "bootstrap runs the images the sealed manifest names, not the ones lying around"
state="$(new_state blue "blue")"
release_run "$state" "$SCRIPTS/bootstrap.sh" || fail "bootstrap failed"
for image in web admin-web chat-service media-service auth-service; do
  assert_equals "$image is pinned to the manifest's digest" \
    "$(manifest_digest "$MANIFEST_A" "$image")" \
    "$(applied_image_digest "$state" baseline.yaml "$image")"
done
# The migration Job is rendered separately and is just as much part of the
# release: a schema change from another build is not a smaller problem.
assert_equals "the migration Job runs the manifest's image" \
  "$(manifest_digest "$MANIFEST_A" migrations)" \
  "$(applied_image_digest "$state" migrations.yaml migrations)"
assert_equals "no external artefact digest reached the baseline" "" \
  "$(grep -o "sha256:$(printf '0%.0s' {1..63})1" "$state/applied/baseline.yaml" | sort -u)"
pass

# The pair the review asked for: one commit, two builds. The images and the
# release id have to move together, so a run of A can never produce A's identity
# over B's images.
begin "a rebuild of the same commit changes both the identity and the images"
[[ "$RELEASE_ID_A" != "$RELEASE_ID_A_REBUILT" ]] ||
  fail "two builds of $RELEASE_A share a release id; the identity distinguishes nothing"
state="$(new_state blue "blue")"
MANIFEST_DIR="$MANIFEST_A_REBUILT" release_run "$state" "$SCRIPTS/bootstrap.sh" ||
  fail "bootstrap of the rebuild failed"
assert_equals "the commit is unchanged" "$RELEASE_A" \
  "$(applied_annotation "$state" baseline.yaml nchat.io/release-sha)"
assert_equals "the identity is the rebuild's" "$RELEASE_ID_A_REBUILT" \
  "$(applied_annotation "$state" baseline.yaml nchat.io/release-id)"
assert_equals "web runs the rebuild's image" \
  "$(manifest_digest "$MANIFEST_A_REBUILT" web)" \
  "$(applied_image_digest "$state" baseline.yaml web)"
[[ "$(applied_image_digest "$state" baseline.yaml web)" != "$(manifest_digest "$MANIFEST_A" web)" ]] ||
  fail "the rebuild was applied with the first build's image"
pass

# A manifest that no longer describes a complete release cannot identify one,
# whether the damage is a missing image or an unusable digest. Both are refused
# by the same contract, and both are refused before anything is applied.
begin "bootstrap refuses a resealed manifest that is missing an image"
state="$(new_state blue "blue")"
MANIFEST_DIR="$(reseal_manifest incomplete 'del(.images.web)')" status=0
release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 1 "$status"
[[ ! -d "$state/applied" ]] || fail "applied a baseline from an incomplete manifest"
pass

begin "bootstrap refuses a resealed manifest carrying an unusable digest"
state="$(new_state blue "blue")"
MANIFEST_DIR="$(reseal_manifest bad-digest '.images.web = "not-a-digest"')" status=0
release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 1 "$status"
[[ ! -d "$state/applied" ]] || fail "applied a baseline pinning an unusable digest"
pass

# The identity has to be derived, not assumed: a manifest for another commit
# describes another release, however well-formed it is.
begin "bootstrap refuses a manifest that seals a different commit"
state="$(new_state blue "blue")"
MANIFEST_DIR="$MANIFEST_B" status=0
release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 1 "$status"
[[ ! -d "$state/applied" ]] || fail "applied a baseline whose identity was never established"
grep -q "seals release" "$WORK/err.txt" || fail "did not name the mismatch"
pass

begin "bootstrap refuses a manifest that is not sealed"
state="$(new_state blue "blue")"
unsealed="$WORK/unsealed-manifest"
rm -rf "$unsealed"; cp -a "$MANIFEST_A" "$unsealed"
printf 'tampered' >>"$unsealed/release-manifest.json"
MANIFEST_DIR="$unsealed" status=0
release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 1 "$status"
[[ ! -d "$state/applied" ]] || fail "applied a baseline from an unsealed manifest"
pass

begin "bootstrap refuses to start with no manifest to identify the release"
state="$(new_state blue "blue")"
MANIFEST_DIR="$WORK/no-such-manifest" status=0
release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 1 "$status"
[[ ! -d "$state/applied" ]] || fail "applied a baseline with no derivable release id"
pass

# Bootstrap and deploy establish slots by different routes; a baseline the later
# gates cannot read the same way as a candidate is a first release that can
# never be promoted away from.
begin "bootstrap and deploy stamp the same identity contract"
state="$(new_state blue "blue")"
release_run "$state" "$SCRIPTS/bootstrap.sh" || fail "bootstrap failed"
deployed="$(new_state blue "blue green")"
release_run "$deployed" "$SCRIPTS/deploy.sh" || fail "deploy failed"
assert_equals "both stamp the same commit" \
  "$(applied_annotation "$state" baseline.yaml nchat.io/release-sha)" \
  "$(applied_annotation "$deployed" candidate.yaml nchat.io/release-sha)"
assert_equals "both stamp the same release id" \
  "$(applied_annotation "$state" baseline.yaml nchat.io/release-id)" \
  "$(applied_annotation "$deployed" candidate.yaml nchat.io/release-id)"
pass

echo
echo "--- bootstrap -> baseline smoke (first production, end to end) ---"

# The gap the third review found: bootstrap and smoke each passed alone, and were
# incompatible with each other. Bootstrap leaves Blue selected by the stable
# Services, and the candidate smoke refuses a slot that holds traffic -- so the
# documented first launch could never be completed. This exercises the two in
# sequence, which is the only way that class of contradiction shows up.
begin "bootstrap then baseline smoke completes the first production sequence"
state="$(new_state blue "blue")"
release_run "$state" "$SCRIPTS/bootstrap.sh" || fail "bootstrap failed"
# Bootstrap leaves Blue selected: that is the baseline, not a mistake.
assert_all_on "$state" blue
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 0 "$status"
grep -q "ACTIVE   : blue" "$WORK/out.txt" || fail "status does not report Blue as active"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target blue --baseline || status=$?
expect_exit 0 "$status"
grep -q "mode: baseline" "$WORK/out.txt" || fail "did not run in baseline mode"
grep -q "baseline: blue is the only deployed slot" "$WORK/out.txt" || fail "baseline preconditions not reported"
grep -q "NCHAT_PROD_SMOKE_CONFIRMED=blue:$RELEASE_A" "$WORK/out.txt" ||
  fail "baseline smoke did not bind evidence to the release"
pass

begin "the candidate smoke still refuses a live slot without --baseline"
state="$(new_state blue "blue")"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target blue || status=$?
expect_exit 1 "$status"
grep -q "already selected by" "$WORK/err.txt" || fail "isolation rule was weakened"
pass

begin "--baseline is refused for green"
state="$(new_state green "green")"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target green --baseline || status=$?
expect_exit 1 "$status"
grep -q "applies only to the baseline slot" "$WORK/err.txt" || fail "accepted a non-baseline slot"
pass

begin "--baseline is refused when the slot is not what the Services select"
state="$(new_state green "blue green")"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target blue --baseline || status=$?
expect_exit 1 "$status"
grep -q "not what the stable Services select" "$WORK/err.txt" || fail "accepted an unselected baseline"
pass

begin "--baseline is refused in a mixed state"
state="$(new_state blue "blue")"
printf 'green' >"$state/services/chat-service"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target blue --baseline || status=$?
expect_exit 1 "$status"
grep -q "do not agree on a slot" "$WORK/err.txt" || fail "accepted a mixed state as a baseline"
pass

begin "--baseline is refused once the other slot has been deployed"
state="$(new_state blue "blue green")"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target blue --baseline || status=$?
expect_exit 1 "$status"
grep -q "past its baseline" "$WORK/err.txt" || fail "baseline mode survived past the first release"
pass

begin "an unknown smoke argument is refused"
state="$(new_state blue "blue")"
status=0; run "$state" "$SCRIPTS/smoke.sh" --target blue --force || status=$?
expect_exit 1 "$status"
pass

echo
echo "--- migration coordination ---"

# Deploys used to delete the migration Job before applying the next one, which
# kills a migration another operator is running: the pod dies, its advisory lock
# is released, and the schema_migrations row it marked in progress is left
# behind for the next run to refuse. Nothing below may delete an active Job.
JOB_A="nchat-migrations-${RELEASE_A:0:12}"
JOB_B="nchat-migrations-${RELEASE_B:0:12}"

begin "the first deploy of a release creates its own migration Job"
state="$(new_state blue "blue green")"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 0 "$status"
grep -q "$JOB_A" "$state/wait-log" || fail "did not wait on the release's own Job"
[[ ! -f "$state/delete-log" ]] || fail "deleted something during a clean migration"
pass

begin "a second deploy of the same release reuses the completed migration"
state="$(new_state blue "blue green")"
printf '1 0\n' >"$state/jobs/$JOB_A"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 0 "$status"
grep -q "already completed" "$WORK/out.txt" || fail "did not reuse the completed migration"
[[ ! -f "$state/delete-log" ]] || fail "deleted a completed migration Job"
grep -q "migrations.yaml" "$state/apply-log" && fail "re-applied a migration that had already run"
pass

begin "a deploy never deletes a migration Job that is still running"
state="$(new_state blue "blue green")"
printf '0 0\n' >"$state/jobs/$JOB_A"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 0 "$status"
grep -q "already running" "$WORK/out.txt" || fail "did not recognise the running migration"
[[ ! -f "$state/delete-log" ]] || fail "deleted an active migration Job"
pass

begin "a migration running for another release blocks the deploy"
state="$(new_state blue "blue green")"
printf '0 0\n' >"$state/jobs/$JOB_B"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
grep -q "in progress for another release" "$WORK/err.txt" || fail "allowed two releases to migrate at once"
[[ ! -f "$state/delete-log" ]] || fail "deleted another release's active Job"
grep -q "migrations.yaml" "$state/apply-log" 2>/dev/null && fail "applied a second concurrent migration"
pass

begin "a failed migration blocks the deploy and is preserved for diagnosis"
state="$(new_state blue "blue green")"
printf '0 1\n' >"$state/jobs/$JOB_A"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
grep -q "Failed state" "$WORK/err.txt" || fail "did not report the failed migration"
grep -q "kubectl logs job/$JOB_A" "$WORK/err.txt" || fail "did not offer an inspection command"
[[ ! -f "$state/delete-log" ]] || fail "destroyed the evidence of a failed migration"
[[ -f "$state/jobs/$JOB_A" ]] || fail "the failed Job was removed"
pass

begin "bootstrap follows the same rules and never deletes an active Job"
state="$(new_state blue "blue")"
printf '0 0\n' >"$state/jobs/$JOB_A"
status=0; release_run "$state" "$SCRIPTS/bootstrap.sh" || status=$?
expect_exit 0 "$status"
[[ ! -f "$state/delete-log" ]] || fail "bootstrap deleted an active migration Job"
pass

echo
echo "--- deploy ---"

begin "deploy refuses a release that is not a commit SHA"
state="$(new_state blue "blue green")"
RELEASE_SHA=abc status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
[[ ! -f "$state/apply-log" ]] || fail "applied a candidate for an unidentified release"
pass

begin "deploy refuses an unexpected kube context"
state="$(new_state blue "blue green")"
printf 'some-other-cluster' >"$state/context"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
[[ ! -f "$state/apply-log" ]] || fail "applied a candidate against the wrong cluster"
pass

begin "deploy stops when the migration fails and never applies the candidate"
state="$(new_state blue "blue green")"
printf '1' >"$state/migration-fails"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
grep -qE "migration .* did not complete" "$WORK/err.txt" || fail "did not report the migration failure"
[[ ! -f "$state/rollout-log" ]] || fail "waited on a candidate that was never applied"
pass

begin "deploy fails when the candidate never becomes Ready"
state="$(new_state blue "blue green")"
printf '1' >"$state/rollout-fails"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
grep -q "did not become Ready" "$WORK/err.txt" || fail "did not report the rollout failure"
pass

begin "deploy stops when the namespace cannot hold a second slot"
state="$(new_state blue "blue green")"
printf '1' >"$state/quota/hard-cpu"
printf '900m' >"$state/quota/used-cpu"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
grep -qE "cannot hold slot .* at production capacity" "$WORK/err.txt" || fail "did not report the shortfall"
[[ ! -f "$state/rollout-log" ]] || fail "waited on a candidate that could not be admitted"
pass

begin "deploy stops when capacity cannot be determined at all"
state="$(new_state blue "blue green")"
rm -rf "$state/quota" "$state/node-allocatable" "$state/cluster-pods"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
grep -q "inconclusive" "$WORK/err.txt" || fail "did not report the preflight as inconclusive"
pass

begin "deploy never moves traffic to the candidate"
state="$(new_state blue "blue green")"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 0 "$status"
assert_all_on "$state" blue
[[ ! -s "$state/patch-log" ]] || fail "deploy patched a Service; promotion is cutover's job"
pass

echo
echo "--- the requested candidate slot ---"

# The pipeline resolves the candidate from its own reading of the stable
# Services -- the reading its before/after selector proof is built on -- and
# hands that slot over. Deriving it again here would make two decisions out of
# one: a cutover landing between the two readings would leave the pipeline
# smoking and reporting one slot while this script built the other.
#
# So the request is revalidated, never replaced, and the revalidation happens
# before every mutation.

# deploy.sh with a slot requested, scoped to this one call.
#
# Not `CANDIDATE_SLOT=green status=0; release_run ...`: that is two assignments
# rather than a prefixed command, so the value outlives the case and the next
# one inherits it. An env prefix on a function call is restored afterwards, so
# each case below starts from nothing requested.
deploy_requesting() {
  local slot="$1" state="$2"
  CANDIDATE_SLOT="$slot" release_run "$state" "$SCRIPTS/deploy.sh"
}

begin "a requested candidate that is still the idle slot is the one deployed"
state="$(new_state blue "blue green")"
status=0; deploy_requesting green "$state" || status=$?
expect_exit 0 "$status"
grep -q "candidate.yaml" "$state/apply-log" || fail "did not apply the candidate"
grep -q -- "-green" "$state/rollout-log" || fail "did not roll out the requested slot"
grep -q -- "-blue" "$state/rollout-log" && fail "rolled out the slot serving production"
assert_all_on "$state" blue
pass

# The divergence case: the request was made against a cluster where Blue was
# active, and by the time the deploy runs the stable Services select Green. The
# idle slot is now Blue, so the request no longer describes the cluster.
begin "a requested candidate the cluster no longer agrees with stops the deploy"
state="$(new_state green "blue green")"
status=0; deploy_requesting green "$state" || status=$?
expect_exit 1 "$status"
grep -q "stable Services moved" "$WORK/err.txt" || fail "did not report the divergence"
pass

# Where the refusal lands matters as much as that it happens. Everything below
# is downstream of the gate, and none of it may have run.
begin "the divergence stops the deploy before the migration"
state="$(new_state green "blue green")"
status=0; deploy_requesting green "$state" || status=$?
expect_exit 1 "$status"
[[ ! -f "$state/wait-log" ]] || fail "ran a migration for a candidate it then refused"
pass

begin "the divergence stops the deploy before the candidate is applied"
state="$(new_state green "blue green")"
status=0; deploy_requesting green "$state" || status=$?
expect_exit 1 "$status"
[[ ! -f "$state/apply-log" ]] || fail "applied a candidate the cluster no longer agreed with"
[[ ! -f "$state/rollout-log" ]] || fail "waited on a candidate that was never applied"
[[ ! -s "$state/patch-log" ]] || fail "touched a stable Service while refusing"
pass

# The failure this gate exists for. Silently deploying Blue instead -- the slot
# the cluster now calls idle -- would leave the pipeline smoking Green, and the
# release would be validated on a slot nobody deployed.
begin "a divergent request never falls back to the other slot"
state="$(new_state green "blue green")"
status=0; deploy_requesting green "$state" || status=$?
expect_exit 1 "$status"
[[ ! -f "$state/rollout-log" ]] || fail "deployed some slot after refusing the requested one"
pass

# The active slot can never be its own opposite, so asking for it is always a
# divergence -- and the one that would deploy over live production.
begin "the slot serving production is never accepted as a candidate"
state="$(new_state blue "blue green")"
status=0; deploy_requesting blue "$state" || status=$?
expect_exit 1 "$status"
[[ ! -f "$state/apply-log" ]] || fail "deployed over the slot carrying production traffic"
pass

begin "a requested slot that is not a slot at all is refused"
state="$(new_state blue "blue green")"
status=0; deploy_requesting production "$state" || status=$?
expect_exit 1 "$status"
[[ ! -f "$state/apply-log" ]] || fail "deployed something for an unrecognised slot"
pass

# The manual flow of the runbook passes nothing, and must keep deriving the
# candidate exactly as it always has.
begin "with no slot requested the canonical derivation still stands"
state="$(new_state blue "blue green")"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 0 "$status"
grep -q -- "-green" "$state/rollout-log" || fail "did not derive Green as the idle slot"
grep -q "candidate slot: green" "$WORK/out.txt" || fail "did not report the derived candidate"
pass



echo
echo "--- the candidate carries the requested release ---"

# The gate the production deploy workflow runs after its smoke.
#
# The smoke proves a slot agrees with itself. It cannot prove the slot is
# running the release the run built: a concurrent redeploy of that same slot
# leaves the stable selectors untouched and produces a slot that is equally
# Ready and equally CONSISTENT. Only comparing the observed identity to the
# requested one separates the two, and that is what this exercises -- the real
# helper, against the fake cluster, exactly as the workflow calls it.
identity_run() {
  local state="$1" slot="$2" expected="$3"
  FAKE_STATE_DIR="$state" bash -c '
    set -Eeuo pipefail
    source "$1/lib.sh"
    require_slot_release_identity "$2" "$3"
  ' _ "$SCRIPTS" "$slot" "$expected" >"$WORK/out.txt" 2>"$WORK/err.txt"
}

# Two scripts once defined a require_release_identity: lib.sh for a slot, and
# cutover.sh for the sealed manifest it is promoting. cutover.sh sources lib.sh
# and then defines its own, so which one ran depended on the order of a `source`
# line, and the two took different arguments. Nothing failed, because the local
# definition happened to come last -- which is the kind of correctness that
# stops being true the moment someone moves a line.
#
# Generalised rather than pinned to those two names, but only over the shape
# that is actually a hazard: a name lib.sh defines and a script that sources
# lib.sh defines again. Each entrypoint having its own main() or run_migrations()
# is not that -- those scripts are executed, never sourced into one another.
begin "no script redefines a function it inherits from lib.sh"
shared="$(sed -n 's/^\([a-z_][a-z0-9_]*\)() {$/\1/p' "$SCRIPTS/lib.sh" | LC_ALL=C sort -u)"
shadowed=""
for script in "$SCRIPTS"/*.sh; do
  [[ "$(basename "$script")" == lib.sh ]] && continue
  grep -q 'source .*lib\.sh' "$script" || continue
  for name in $(sed -n 's/^\([a-z_][a-z0-9_]*\)() {$/\1/p' "$script"); do
    grep -qxF "$name" <<<"$shared" && shadowed+="$(basename "$script"):$name "
  done
done
[[ -z "$shadowed" ]] || fail "redefines a lib.sh function: $shadowed"
pass

begin "cutover keeps its own release identity helper after sourcing lib.sh"
# The shared helper takes a slot and an expected identity; cutover's takes one
# id and reads the sealed manifest. Sourcing lib.sh must not change which of
# them cutover resolves, so the local one is asserted by its own behaviour:
# with no manifest directory it refuses and says so.
FAKE_STATE_DIR="$(new_state blue "blue green")" \
  NCHAT_PROD_RELEASE_MANIFEST_DIR="" bash -c '
    set -uo pipefail
    source "$1/lib.sh"
    # shellcheck disable=SC1090
    source <(sed -n "/^require_release_identity() {/,/^}/p" "$1/cutover.sh")
    require_release_identity deadbeef
  ' _ "$SCRIPTS" >"$WORK/out.txt" 2>"$WORK/err.txt" && status=0 || status=$?
expect_exit 1 "$status"
grep -q "NCHAT_PROD_RELEASE_MANIFEST_DIR must name the directory" "$WORK/err.txt" ||
  fail "sourcing lib.sh displaced cutover's own helper"
pass

begin "the requested release is what the candidate is running"
state="$(new_state blue "blue green")"
status=0
identity_run "$state" green "$(identity "$RELEASE_A" "$RELEASE_ID_A")" || status=$?
expect_exit 0 "$status"
pass

# The redeploy this gate exists for: a different commit, deployed cleanly, so
# the slot is Ready and internally consistent and the smoke would pass.
begin "a candidate running another commit is refused"
state="$(new_state blue "blue green")"
for service in "${SERVICES[@]}"; do
  set_release "$state" "$service" green "$RELEASE_B"
done
status=0
identity_run "$state" green "$(identity "$RELEASE_A" "$RELEASE_ID_A")" || status=$?
expect_exit 1 "$status"
grep -q "expected 'CONSISTENT $RELEASE_A" "$WORK/err.txt" || fail "did not name the expected release"
pass

# The half a commit cannot answer: the slot is running RELEASE_A sealed as
# RELEASE_ID_A, and what is expected is the same commit built again -- different
# image bytes, so a different seal, and RELEASE_ID_A_REBUILT is that seal.
#
# The commit is identical on both sides on purpose. Pairing RELEASE_A with some
# other commit's seal would be refused for the SHA as much as for the id, and
# would prove nothing a SHA-only comparison does not already catch. Only a
# genuine rebuild isolates the half that the commit cannot see.
begin "a rebuild of the same commit is refused"
[[ "$RELEASE_ID_A" != "$RELEASE_ID_A_REBUILT" ]] ||
  fail "the rebuild fixture seals the same id as the original build"
state="$(new_state blue "blue green")"
status=0
identity_run "$state" green "$(identity "$RELEASE_A" "$RELEASE_ID_A_REBUILT")" || status=$?
expect_exit 1 "$status"
grep -q "$RELEASE_A:$RELEASE_ID_A_REBUILT" "$WORK/err.txt" ||
  fail "did not name the rebuild's identity as the expected one"
pass

begin "a candidate still rolling out is refused"
state="$(new_state blue "blue green")"
set_rollout "$state" chat-service-green 2 2 2 0 2 2 0
status=0
identity_run "$state" green "$(identity "$RELEASE_A" "$RELEASE_ID_A")" || status=$?
expect_exit 1 "$status"
grep -q "ROLLING_OUT" "$WORK/err.txt" || fail "did not report the slot as rolling out"
pass

begin "a candidate whose workloads disagree is refused"
state="$(new_state blue "blue green")"
set_workload_release "$state" chat-service-green "$RELEASE_B"
status=0
identity_run "$state" green "$(identity "$RELEASE_A" "$RELEASE_ID_A")" || status=$?
expect_exit 1 "$status"
grep -q "MIXED" "$WORK/err.txt" || fail "did not report the slot as mixed"
pass

begin "a candidate that was never deployed is refused"
state="$(new_state blue "blue")"
status=0
identity_run "$state" green "$(identity "$RELEASE_A" "$RELEASE_ID_A")" || status=$?
expect_exit 1 "$status"
grep -q "NOT_DEPLOYED" "$WORK/err.txt" || fail "did not report the slot as undeployed"
pass

echo
echo "--- namespace gate ---"

# The gate must be satisfiable by the production deploy identity, which holds a
# namespaced Role and no cluster-scoped permission whatsoever (SEC03). Reading
# the `namespaces` resource is therefore not a check these scripts may perform,
# and the fake kubectl records any attempt so a reintroduction fails here.
assert_no_cluster_scoped_read() {
  [[ ! -f "$1/cluster-scoped-log" ]] ||
    fail "read a cluster-scoped resource: $(tr '\n' ';' <"$1/cluster-scoped-log")"
}

begin "the namespace gate never reads the cluster-scoped namespaces resource"
state="$(new_state blue "blue green")"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 0 "$status"
assert_no_cluster_scoped_read "$state"
pass

begin "no production script asks for a namespace object"
# Comments are stripped first: this file and lib.sh both have to be able to
# name the call they refuse without the check reading its own prose as code.
sed 's/#.*//' "$SCRIPTS"/*.sh |
  grep -nE 'kubectl[^|]*get[[:space:]]+(-[^[:space:]]+[[:space:]]+)*namespaces?\b' &&
  fail "a script reads the cluster-scoped namespaces resource"
pass

begin "deploy passes the gate without a cluster-scoped read"
state="$(new_state blue "blue green")"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 0 "$status"
assert_no_cluster_scoped_read "$state"
pass

begin "cutover passes the gate without a cluster-scoped read"
state="$(new_state blue "blue green")"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 0 "$status"
assert_all_on "$state" green
assert_no_cluster_scoped_read "$state"
pass

begin "rollback passes the gate without a cluster-scoped read"
state="$(new_state green "blue green")"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "5xx after cutover" || status=$?
expect_exit 0 "$status"
assert_all_on "$state" blue
assert_no_cluster_scoped_read "$state"
pass

# The gate refuses three different answers from the API, and the fixture has to
# be able to produce them apart or the cases below all prove the same thing.
# This asserts the fake's own contract, once, so the script cases that follow
# can each name the situation they exercise.
assert_fake_services_error() {
  local result="$1" pattern="$2" state="$3" status=0
  printf '%s' "$result" >"$state/services-list-result"
  FAKE_STATE_DIR="$state" kubectl get services -n nchat-prod \
    >"$WORK/out.txt" 2>"$WORK/err.txt" || status=$?
  [[ "$status" -ne 0 ]] || fail "$result answered the listing with success"
  grep -q "$pattern" "$WORK/err.txt" ||
    fail "$result did not answer '$pattern': $(cat "$WORK/err.txt")"
}

begin "the fake answers NotFound, Forbidden and an API error apart"
state="$(new_state blue "blue green")"
assert_fake_services_error not-found 'NotFound' "$state"
! grep -q 'Forbidden' "$WORK/err.txt" || fail "NotFound and Forbidden are the same answer"
assert_fake_services_error forbidden 'Forbidden' "$state"
! grep -q 'NotFound' "$WORK/err.txt" || fail "Forbidden and NotFound are the same answer"
assert_fake_services_error api-error 'Unable to connect to the server' "$state"
! grep -qE 'NotFound|Forbidden' "$WORK/err.txt" ||
  fail "a transport error was answered as an authorisation decision"
pass

# An unset result is the ordinary namespace, and an unrecognised one is still a
# failure: a typo in a fixture must not become a passing read.
begin "an unrecognised listing result is refused, not silently accepted"
state="$(new_state blue "blue green")"
printf 'sucess' >"$state/services-list-result"
status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
expect_exit 1 "$status"
pass

# The three failures, one per production flow, each proving the flow stopped at
# the gate and mutated nothing after it.
begin "deploy stops when the API reports the namespace NotFound"
state="$(new_state blue "blue green")"
printf 'not-found' >"$state/services-list-result"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
grep -q "does not exist or is not readable" "$WORK/err.txt" || fail "did not report the namespace gate"
[[ ! -f "$state/apply-log" ]] || fail "applied a manifest after the gate had failed"
[[ ! -f "$state/wait-log" ]] || fail "waited on a migration after the gate had failed"
pass

begin "cutover stops when the namespaced read is Forbidden"
state="$(new_state blue "blue green")"
printf 'forbidden' >"$state/services-list-result"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
grep -q "does not exist or is not readable" "$WORK/err.txt" || fail "did not fail closed on a refused read"
[[ ! -s "$state/patch-log" ]] || fail "patched a Service after the gate had failed"
assert_all_on "$state" blue
pass

begin "rollback stops when the API cannot be reached at all"
state="$(new_state green "blue green")"
printf 'api-error' >"$state/services-list-result"
status=0; run "$state" "$SCRIPTS/rollback.sh" --target blue "5xx after cutover" || status=$?
expect_exit 1 "$status"
grep -q "does not exist or is not readable" "$WORK/err.txt" || fail "did not report the namespace gate"
[[ ! -s "$state/patch-log" ]] || fail "patched a Service after the gate had failed"
assert_all_on "$state" green
pass

begin "every failed listing is fail-closed, whatever the API answered"
state="$(new_state blue "blue green")"
for result in not-found forbidden api-error; do
  printf '%s' "$result" >"$state/services-list-result"
  status=0; run "$state" "$SCRIPTS/status.sh" || status=$?
  expect_exit 1 "$status"
  grep -q "does not exist or is not readable" "$WORK/err.txt" ||
    fail "$result was not reported as an unusable namespace"
done
pass

# The namespace being wrong is a separate claim, and it is made without
# injecting any failure: the fixture answers for its own namespace and no other,
# so a rehearsal pointed somewhere else is refused rather than quietly answered
# by whatever namespace the kubeconfig happens to select.
begin "the gate never falls back to another namespace"
state="$(new_state blue "blue green")"
[[ ! -f "$state/services-list-result" ]] || fail "the fixture injected a failure into this case"
export NCHAT_PROD_NAMESPACE=default
SMOKE="$(evidence blue "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
unset NCHAT_PROD_NAMESPACE
expect_exit 1 "$status"
grep -q "namespace 'default' does not exist or is not readable" "$WORK/err.txt" ||
  fail "accepted a namespace the identity was not bound to"
[[ ! -s "$state/patch-log" ]] || fail "patched a Service in the wrong namespace"
assert_all_on "$state" blue
pass

begin "the context gate still refuses an unexpected cluster"
state="$(new_state blue "blue green")"
printf 'some-other-cluster' >"$state/context"
SMOKE="$(evidence green "$RELEASE_A" "$RELEASE_ID_A")" MANIFEST_DIR="$MANIFEST_A" status=0; run "$state" "$SCRIPTS/cutover.sh" --target green || status=$?
expect_exit 1 "$status"
grep -q "expected 'nchat-prod-deployer'" "$WORK/err.txt" || fail "did not refuse the context"
[[ ! -s "$state/patch-log" ]] || fail "patched a Service in the wrong cluster"
assert_all_on "$state" blue
pass


echo
echo "--- capacity under the namespaced deploy identity ---"
#
# nchat-prod-deployer holds a Role in nchat-prod and nothing cluster-scoped: it
# is refused `get nodes` and `get pods --all-namespaces`, which is where the
# preflight got three of its four inputs. The node these workloads share is 94%
# committed, most of it by other namespaces, so answering from nchat-prod alone
# would report room that is not there.
#
# So the cluster-wide half is collected elsewhere and delivered as evidence, and
# these cases are the whole claim: a deploy that completes with both reads
# refused, and one that stops -- before the migration and before any apply --
# whenever the evidence cannot be believed.
assert_no_cluster_wide_read() {
  [[ ! -f "$1/cluster-wide-log" ]] ||
    fail "read a cluster-wide resource: $(tr '\n' ';' <"$1/cluster-wide-log")"
}

# Nothing after the gate may have run.
assert_nothing_deployed() {
  [[ ! -f "$1/wait-log" ]] || fail "ran the migration despite the capacity gate"
  [[ ! -f "$1/apply-log" ]] || fail "applied a manifest despite the capacity gate"
  [[ ! -f "$1/rollout-log" ]] || fail "waited on a candidate that was never admitted"
}

# The collection a trusted read-only context performs, against the same fixture
# cluster and before it starts refusing the cluster-wide reads.
collect_evidence() {
  local state="$1" out="$2"
  rm -rf "$out"
  FAKE_STATE_DIR="$state" bash "$SCRIPTS/capacity-evidence.sh" "$out" >/dev/null ||
    fail "could not collect capacity evidence"
  rm -f "$state/cluster-wide-log"
  printf '1' >"$state/deny-cluster-wide"
}

begin "deploy passes the capacity gate from evidence with Nodes and other namespaces refused"
state="$(new_state blue "blue green")"
collect_evidence "$state" "$WORK/evidence"
EVIDENCE="$WORK/evidence" status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 0 "$status"
assert_no_cluster_wide_read "$state"
assert_no_cluster_scoped_read "$state"
[[ ! -f "$state/secret-read-log" ]] || fail "deploy read a Secret"
grep -q "candidate.yaml" "$state/apply-log" || fail "never applied the candidate"
[[ ! -s "$state/patch-log" ]] || fail "deploy patched a Service; promotion is cutover's job"
pass

begin "deploy without evidence cannot verify capacity for this identity and stops"
state="$(new_state blue "blue green")"
printf '1' >"$state/deny-cluster-wide"
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
grep -q "inconclusive" "$WORK/err.txt" || fail "did not report the preflight as inconclusive"
assert_nothing_deployed "$state"
pass

# The evidence has to fail closed, and it has to fail before anything moves.
begin "deploy stops before the migration when the evidence cannot be believed"
state="$(new_state blue "blue green")"
collect_evidence "$state" "$WORK/evidence-bad"
printf 'Running|node-a|1m 1Mi 1Mi\n' >>"$WORK/evidence-bad/cluster-requests.txt"
EVIDENCE="$WORK/evidence-bad" status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
grep -q "capacity evidence" "$WORK/err.txt" || fail "did not name the evidence as the reason"
assert_nothing_deployed "$state"
pass

# A real shortfall is still a shortfall when it is read from a snapshot.
begin "deploy stops when the evidence shows the cluster cannot hold the candidate"
state="$(new_state blue "blue green")"
collect_evidence "$state" "$WORK/evidence"
printf '1' >"$state/quota/hard-cpu"
printf '900m' >"$state/quota/used-cpu"
EVIDENCE="$WORK/evidence" status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
expect_exit 1 "$status"
grep -qE "cannot hold slot .* at production capacity" "$WORK/err.txt" || fail "did not report the shortfall"
assert_nothing_deployed "$state"
pass

# Malformed evidence is unusable input, and unusable input is not a gap an
# operator can acknowledge. The checksums are recomputed after each corruption,
# so these prove that a well-formed envelope does not make the contents
# believable -- and that the override reaches INCONCLUSIVE and nothing else.
#
# The list covers a line with no structure, a negative quantity, one that
# overflows to infinity, and a Pod that holds no capacity and would once have
# been dropped before anything read what it said. Each is run with the override
# off and on: exit 3 is not exit 2, and only exit 2 is something to acknowledge.
resign_evidence() {
  (cd "$1" && sha256sum node-allocatable.txt cluster-requests.txt cluster-pods.txt >sha256sums.txt)
}

begin "malformed evidence stops the deploy, and the override cannot release it"
state="$(new_state blue "blue green")"
collect_evidence "$state" "$WORK/evidence-pristine"
for corruption in "cluster-pods.txt:not-a-pod-record" \
  "node-allocatable.txt:not-a-node-record" "cluster-requests.txt:Running|node-a" \
  "cluster-requests.txt:Running|node-a|-100m 256Mi 1Gi" \
  "cluster-requests.txt:Running|node-a|1e309 2Gi 64Mi" \
  "cluster-requests.txt:Succeeded|node-a|not-a-quantity"; do
  rm -rf "$WORK/evidence-malformed"
  cp -r "$WORK/evidence-pristine" "$WORK/evidence-malformed"
  printf '%s\n' "${corruption#*:}" >"$WORK/evidence-malformed/${corruption%%:*}"
  resign_evidence "$WORK/evidence-malformed"
  for override in 0 1; do
    export NCHAT_PROD_ALLOW_INCONCLUSIVE_CAPACITY="$override"
    EVIDENCE="$WORK/evidence-malformed" status=0
    release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
    unset NCHAT_PROD_ALLOW_INCONCLUSIVE_CAPACITY
    expect_exit 1 "$status"
    grep -q "refused its input" "$WORK/err.txt" ||
      fail "${corruption%%:*} with override=$override was not refused as unusable input"
    ! grep -q "explicit acknowledgement" "$WORK/err.txt" ||
      fail "${corruption%%:*} was waved through as an inconclusive dimension"
    ! grep -qE "Traceback|OverflowError" "$WORK/err.txt" ||
      fail "${corruption%%:*} left by way of a traceback"
    assert_nothing_deployed "$state"
  done
done
pass

# The override is not the fix for a namespaced identity -- evidence is -- but it
# stays what it was: explicit, opt-in, and never the default.
begin "an unverifiable capacity picture still needs the operator's explicit acknowledgement"
state="$(new_state blue "blue green")"
printf '1' >"$state/deny-cluster-wide"
export NCHAT_PROD_ALLOW_INCONCLUSIVE_CAPACITY=1
status=0; release_run "$state" "$SCRIPTS/deploy.sh" || status=$?
unset NCHAT_PROD_ALLOW_INCONCLUSIVE_CAPACITY
expect_exit 0 "$status"
grep -q "explicit acknowledgement" "$WORK/err.txt" || fail "proceeded without saying so"
pass


echo
if [ "$FAILURES" -gt 0 ]; then
  echo "production blue/green script tests failed with $FAILURES failure(s)." >&2
  exit 1
fi
echo "production blue/green script tests passed."
