apiVersion: v1
kind: ConfigMap
metadata:
  name: nchat-config
  namespace: nchat
  annotations:
    nchat.nicrepository.io/data-services: placeholders-only
data:
  APP_ENV: development
  LOG_LEVEL: info
