apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nchat
resources:
  - ../../base
  - ingress.yaml
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/instance: k3s-dev
images:
  - name: ghcr.io/nicrepository/nchat/web
    newTag: 0.0.0
  - name: ghcr.io/nicrepository/nchat/admin-web
    newTag: 0.0.0
  - name: ghcr.io/nicrepository/nchat/auth-service
    newTag: 0.0.0
  - name: ghcr.io/nicrepository/nchat/chat-service
    newTag: 0.0.0
  - name: ghcr.io/nicrepository/nchat/file-service
    newTag: 0.0.0
  - name: ghcr.io/nicrepository/nchat/notification-service
    newTag: 0.0.0
  - name: ghcr.io/nicrepository/nchat/admin-service
    newTag: 0.0.0
  - name: ghcr.io/nicrepository/nchat/search-service
    newTag: 0.0.0
  - name: ghcr.io/nicrepository/nchat/media-service
    newTag: 0.0.0
patches:
  - path: namespace-patch.yaml
  - path: configmap-patch.yaml
  - path: patches/web-replicas.yaml
  - path: patches/admin-web-replicas.yaml
  - path: patches/auth-service-replicas.yaml
  - path: patches/chat-service-replicas.yaml
  - path: patches/file-service-replicas.yaml
  - path: patches/notification-service-replicas.yaml
  - path: patches/admin-service-replicas.yaml
  - path: patches/search-service-replicas.yaml
  - path: patches/media-service-replicas.yaml
