apiVersion: v1
kind: PersistentVolume
metadata:
  name: nchat-dev-postgres
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd-geral
  local:
    path: /mnt/hdd-geral/k3s/nchat-dev/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - srv-apps-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nchat-dev-valkey
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd-geral
  local:
    path: /mnt/hdd-geral/k3s/nchat-dev/valkey
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - srv-apps-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nchat-dev-seaweedfs
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd-geral
  local:
    path: /mnt/hdd-geral/k3s/nchat-dev/seaweedfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - srv-apps-01
