apiVersion: v1
kind: Namespace
metadata:
  name: nchat-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nchat-dev-namespace-maintainer
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    resourceNames:
      - nchat-dev
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nchat-dev-namespace-maintainer
subjects:
  - kind: User
    name: nchat-dev-deployer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: nchat-dev-namespace-maintainer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nchat-dev-deployer
  namespace: nchat-dev
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
      - serviceaccounts
      - persistentvolumeclaims
      - resourcequotas
      - limitranges
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
      - services/proxy
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
  - apiGroups:
      - traefik.io
    resources:
      - middlewares
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nchat-dev-deployer
  namespace: nchat-dev
subjects:
  - kind: User
    name: nchat-dev-deployer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: nchat-dev-deployer
  apiGroup: rbac.authorization.k8s.io
