apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: chat
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/component: chat
  ports:
    - name: http
      port: 8082
      targetPort: http
