apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resource-quota.yaml
  - limit-range.yaml
  - network-policy.yaml
  - configmap.yaml
  - serviceaccounts.yaml
  - web
  - services/auth-service
  - services/chat-service
  - services/file-service
  - services/upload-guard
  - services/notification-service
  - services/admin-service
  - services/search-service
  - services/media-service
