apiVersion: v1
kind: ServiceAccount
metadata:
  name: nchat-web
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: web
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nchat-admin-web
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: admin-web
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nchat-auth-service
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: auth
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nchat-chat-service
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: chat
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nchat-file-service
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: file
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nchat-notification-service
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: notification
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nchat-admin-service
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: admin
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nchat-search-service
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: search
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nchat-media-service
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: media
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nchat-document-converter
  namespace: nchat
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: document-converter
automountServiceAccountToken: false
