apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: clamav-config
    files:
      - clamd.conf
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: nchat
    app.kubernetes.io/part-of: nchat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: clamav
