package service

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"time"

	"github.com/nicrepository/nchat/services/admin-service/internal/domain"
)

const (
	sessionValueBytes = 32
	maxUserAgentRunes = 255

	sessionHashPrefix = "nchat-admin-session-v1:"
	csrfPrefix        = "nchat-admin-csrf-v1:"

	minSecretBytes = 32
)

// AdminSessionStore is the persistence this service needs. Declared here, at
// the consumer, so the HTTP and storage layers stay independent.
type AdminSessionStore interface {
	// AuthorizeHandshake is the strict check, applied once when a chat access
	// token is exchanged for an administrative session.
	AuthorizeHandshake(ctx context.Context, userID string, authSessionID string) (domain.AdminPrincipal, error)
	// ReauthorizeSession is the per-request check. It re-derives the
	// principal's authority without requiring the chat session to have stayed
	// active in a tab nobody is using.
	ReauthorizeSession(ctx context.Context, userID string, authSessionID string) (domain.AdminPrincipal, error)
	CreateSession(ctx context.Context, input domain.AdminSessionInput) (domain.AdminSession, error)
	TouchSession(ctx context.Context, sessionHash string, idleTTL time.Duration) (domain.AdminSession, error)
	RevokeSession(ctx context.Context, sessionHash string, reason string) error
}

// EstablishInput is the server-derived context of a session handshake. Every
// field comes from a validated access token or from the connection itself;
// none is read from the request body.
type EstablishInput struct {
	UserID        string
	AuthSessionID string
	IPAddress     string
	UserAgent     string
}

// EstablishedSession is what the HTTP layer needs to answer the handshake.
// Value is the opaque credential; it goes into an HttpOnly cookie and is never
// written to a response body, a log or the database.
type EstablishedSession struct {
	Value     string
	CSRFToken string
	Session   domain.AdminSession
	Principal domain.AdminPrincipal
}

// AdminSessionService owns the administrative session policy: how a session is
// created, how long it may idle, how long it may live at all, and what ends it.
//
// The policy is deliberately stricter than the chat session's. A console that
// can suspend accounts and read the audit trail is not the same risk as a chat
// tab, so it does not inherit the chat tab's timeouts, and it does not inherit
// its storage either: the credential is an opaque server-generated value in an
// HttpOnly cookie, not a token any script on the page can read.
type AdminSessionService struct {
	store       AdminSessionStore
	secret      []byte
	idleTTL     time.Duration
	absoluteTTL time.Duration
	now         func() time.Time
}

func NewAdminSessionService(store AdminSessionStore, secret string, idleTTL, absoluteTTL time.Duration) (*AdminSessionService, error) {
	if store == nil {
		return nil, errors.New("admin session store is required")
	}
	if len([]byte(secret)) < minSecretBytes {
		return nil, fmt.Errorf("admin session secret must be at least %d bytes", minSecretBytes)
	}
	if idleTTL <= 0 || absoluteTTL <= 0 {
		return nil, errors.New("admin session TTLs must be positive")
	}
	if idleTTL > absoluteTTL {
		return nil, errors.New("admin session idle TTL cannot exceed the absolute TTL")
	}
	return &AdminSessionService{
		store:       store,
		secret:      []byte(secret),
		idleTTL:     idleTTL,
		absoluteTTL: absoluteTTL,
		now:         func() time.Time { return time.Now().UTC() },
	}, nil
}

// Establish authorizes the handshake and mints a fresh administrative session.
//
// Session fixation is structurally impossible here: the credential is
// generated by this method from crypto/rand and returned to the caller. No
// value supplied by the client is ever adopted as a session identifier, so
// there is nothing an attacker can plant in advance for a victim to log in to.
//
// Elevation is a new row every time, never a mutation of an existing one, so
// the credential in the browser after authentication is never the credential
// that was there before it.
func (s *AdminSessionService) Establish(ctx context.Context, input EstablishInput) (EstablishedSession, error) {
	principal, err := s.store.AuthorizeHandshake(ctx, input.UserID, input.AuthSessionID)
	if err != nil {
		return EstablishedSession{}, err
	}
	// A principal with no capability at all is an administrator on paper only.
	// Refusing here keeps a session that could authorize nothing from existing
	// in the first place.
	if principal.Capabilities.IsEmpty() {
		return EstablishedSession{}, domain.ErrForbidden
	}

	value, err := randomValue(sessionValueBytes)
	if err != nil {
		return EstablishedSession{}, fmt.Errorf("generate admin session value: %w", err)
	}
	issuedAt := s.now()
	session, err := s.store.CreateSession(ctx, domain.AdminSessionInput{
		UserID:            input.UserID,
		AuthSessionID:     input.AuthSessionID,
		SessionHash:       s.hash(sessionHashPrefix, value),
		IPAddress:         input.IPAddress,
		UserAgent:         truncate(input.UserAgent, maxUserAgentRunes),
		IdleExpiresAt:     issuedAt.Add(s.idleTTL),
		AbsoluteExpiresAt: issuedAt.Add(s.absoluteTTL),
	})
	if err != nil {
		return EstablishedSession{}, err
	}
	session.UserID = input.UserID
	session.AuthSessionID = input.AuthSessionID
	principal.UserID = input.UserID
	return EstablishedSession{
		Value:     value,
		CSRFToken: s.CSRFToken(session.ID),
		Session:   session,
		Principal: principal,
	}, nil
}

// Authenticate resolves a cookie value into a live session and the current
// capabilities of its owner.
//
// Both halves are re-checked on every call. The session row must still be
// unrevoked and inside both of its windows, and the principal must still be an
// active administrator behind a still-live NChat session. That is what makes
// "the role was removed" and "the login was revoked" take effect on the next
// request rather than at the next login.
func (s *AdminSessionService) Authenticate(ctx context.Context, value string) (domain.AuthenticatedAdmin, error) {
	if value == "" {
		return domain.AuthenticatedAdmin{}, domain.ErrUnauthorized
	}
	session, err := s.store.TouchSession(ctx, s.hash(sessionHashPrefix, value), s.idleTTL)
	if err != nil {
		return domain.AuthenticatedAdmin{}, err
	}
	principal, err := s.store.ReauthorizeSession(ctx, session.UserID, session.AuthSessionID)
	if err != nil {
		return domain.AuthenticatedAdmin{}, err
	}
	if principal.Capabilities.IsEmpty() {
		return domain.AuthenticatedAdmin{}, domain.ErrForbidden
	}
	return domain.AuthenticatedAdmin{Session: session, Principal: principal}, nil
}

// Revoke ends the session behind a cookie value. It is idempotent and never
// reports whether the value matched anything.
func (s *AdminSessionService) Revoke(ctx context.Context, value string, reason string) error {
	if value == "" {
		return nil
	}
	return s.store.RevokeSession(ctx, s.hash(sessionHashPrefix, value), reason)
}

// CSRFToken derives the double-submit token for a session.
//
// Deriving instead of storing keeps the token bound to exactly one session
// without a second table: it cannot be transplanted onto another session, and
// it cannot be forged without the service secret. It is safe to return in a
// response body — it is not a credential on its own, and a cross-site attacker
// cannot read that body.
func (s *AdminSessionService) CSRFToken(sessionID string) string {
	return s.hash(csrfPrefix, sessionID)
}

// ValidateCSRF compares a submitted token against the one this session should
// carry, in constant time.
func (s *AdminSessionService) ValidateCSRF(sessionID string, provided string) bool {
	expected := s.CSRFToken(sessionID)
	return subtle.ConstantTimeCompare([]byte(expected), []byte(provided)) == 1
}

// IdleTTL exposes the configured idle window so the HTTP layer can set a
// cookie lifetime that matches the row it was issued against.
func (s *AdminSessionService) IdleTTL() time.Duration { return s.idleTTL }

func (s *AdminSessionService) hash(prefix string, value string) string {
	mac := hmac.New(sha256.New, s.secret)
	_, _ = mac.Write([]byte(prefix))
	_, _ = mac.Write([]byte(value))
	return hex.EncodeToString(mac.Sum(nil))
}

func randomValue(size int) (string, error) {
	buf := make([]byte, size)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

func truncate(value string, max int) string {
	runes := []rune(value)
	if len(runes) <= max {
		return value
	}
	return string(runes[:max])
}
