---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: nchat-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAuqZDmzctlFeJnbWyfGvqVbJNzJbfjiSYTg+/KObhrWia3XsUM/1VZbvs81RAAgJ8wkhTQKZLOCmgwbqT3Pmo5AwsXgM2zuIfXy3a38ToyBzqzS8eJX9ISdCFRx+aPCxO0eDZ7wmHcbzRJvfSbdzymsy+OF0x0bz1hsclCfHNLP4svdRtGqwmw6pitlHubo2Kg2jpYo5Jp+Z+E4DTAiKNgUlFCjDDV7rAj3tm6x2kYY2j72TufF3MB6AxaLXYtetH5CrJU15VHWHHDs6gl3v5Zt3EA1NsDI2qxX/CiXJHEJdbmBaU0VINH38u0UgBUj4QwnycPZmeNRwLqmsB1jCcbkrxeuTGkDeFE6TDVFZa7u29qSJaLMldf3mwdjRQFBSjKJsYRWnL1QjMoEDOS15kE9JAgNYJedlCnTLAAg0KfMFZkuz+HLdMTHt+accE+CJkrvc8AagwtnZxKelgV+dpimwbzdwD4Uj0/n/2h3ia9MgzehVYpAhx9aTsFERKePLyiiwjrfbu+P0hlP9/AgQn9Wn8GsKQlMIitdtYf7fddvn4rtOE0MHD5sV1FRQwWbkxUydO3xUOVoZLVykLqDqwBGXKDXe5+0mmECeK5oWnarH7/hYfGG5OpVCqlBl6I9KY1jtjz9hLyUcTLBfOuZmtwn5ddVwNydeT4l45JQsw8BtTHpqeNlBY+qVpAmhaJQ7/rw2x7a+/SNCyHJvv1TSTeB95dQPq1vKTrqzooIR2ZbQV70ZLeqbgviQ0pdj2u0wu7eiVvJsqae7d90jcaISsAccGOHd93MpNiiHnjsnVFlcIokwzgDflxJbl2itijFyLI+AsHk5+2+hk4ZrhNibvad8ngUfu+TQQJzcEX1xEaWckmIkXMHKuMsbzT7fx6qb4YG4z0StvKhU6Y/dTunOXRl0SQ9qNMX00DADayv20gNBrnm/4Nf1THKWw=
  template:
    metadata:
      name: ghcr-pull
      namespace: nchat-dev
    type: kubernetes.io/dockerconfigjson
