apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghcr-pull.yaml
  - nchat-file-encryption.yaml
  - nchat-postgres-admin.yaml
  - nchat-postgres-migrator.yaml
  - nchat-postgres-runtime.yaml
  - nchat-secrets.yaml
