---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nchat-postgres-admin
  namespace: nchat-dev
spec:
  encryptedData:
    POSTGRES_ADMIN_PASSWORD: AgCktFAfNiz/elmQjgL6q/e/ImqosxLeeACPQLoC/yKDcYuPkM0uRUpGv348VPFp95nDik75DW55JP7ljQCJY1qH3NQ8KsEuuur8TN9d6yNKhsh1W4KjCO7MfqHp/GoQqkpYvBeVqpmaGkS4dk1YmEVNtdOREQo7SnnUlV6ClXOnFD4kVy2oNrRTaPKG0TPw112xQo7mi+kM9YmbXXD1vVn60A+S9MOBgHoaE+126RW3H393Nw2m5+QSJJsz0iT5Qclp6KvWu+QdoKtgwZlvmR1PSEZx5uSRaqsVBkrqABW7OUte0eb0+82Zc0GunIC++CZZaHmtDUtKR7bx/Zun6W/+rlMum2faj3RSu6MsZMhVtc7UdXcd3HxmAPz5cj+50C/oaJRTuP450d6pvbx73q9Cg6hrdh6JGbqdVYW3i0eH1TeksUVCbtkjrb3qsLWPDEqvCGlkCua5t8noVSYvIWlhr19Ok+YmthccMU1hTJUWLTooXzRLehf7ocoPGLEm5L3ORf8Ibw9mRQimUVTYcO7Q5xiKTFbNKy7yTRj7fL251O7XJD4nIiXwXXuKQPRwEFMWtY/DLBPnw6JSaSta4vqgLjByVy0oer1s8KAZOaame9wLVpDx9UNrhP59lkqM+GeXduMuIcpQS+79f0yLd2DeynkMyfS8i4E0Qh8Br/wEyWrbBx6Fzw6h32yi57ayLGBljxhuUWnRFhDzNON3Ol33OpPglLT/7kWiCPWbMYNK1L3lhBgk8vDFOg7hAIu1SjdHWSqIqzfiXJubIh92L3z7
    POSTGRES_ADMIN_USER: AgC8zAjJzwRAQqmfO43eor/1hxo3GQciPgf65MEJvFlH+bEoK++DXpQxUKfn2TEuqsFsUS8z6fqM8SlHUaiaHleLxV9RpMiPkRuVzfPGov5iwHNh7VYUfZLeaFHG6+LZSHKbhejpTSADkaL0pvyIFGerX06/ZK0XWmiin9D/wtCdGyMR4N5rCt8igW5aQhlKmMka71n+Az7Bf6h7sZ4k/Ccz9R2ydKNRAiSwY4We4iEdTRiALPIVV9zopFV6pP1jVtkJ90mCvO/WE62c+7uhSoAUen2UVC57axiPOMjd38AhewIsZ2CTsSBdVmiUtCazFv4YTV8Wfq2pdKy754lzIs4aGnkKz8gVBreBR4k5rue/iUtyB5EL/jO821tmW8OcKl9q2lJXe4130pNWcVJyNMRLV0OGhwTZNS3IFRDkoqbe+HNDGHbX84OsaHHBpV5iv6Z/MVO+I+h/dPB0sj3zZQ2EbQZ8m48mqajwPgiQu3kon736iwbv7FsD6aa/dodXlD6WSS4pscVj3457RkoQRnghaASL8SGNYYrwVgHPrQoqsvJz9cPogGRrBWTQI7l5MZZEDqV+L+Raka40emsJWcusUD6Kt0qZzr8tF3Xq47CeQxX/a64UAVwwgC2GhuJ/w/qzuvpwul/1NNXqxUDsusSXk4LsYankaUHyT+G+gi0gJWFYS4p2cKcooYv3fv2+ewRUQYvlKxTF3A==
  template:
    metadata:
      name: nchat-postgres-admin
      namespace: nchat-dev
